name: Create a report on Discussion weekly

on:
  schedule:
    - cron: 0 0 * * 1  # At 00:00 (UTC-0) on every monday.

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Scan
        id: report
        run: >
          # MUST use GNU sed, not BSD sed!
          git --no-pager  log --no-color --since='1 week ago' -p -U0 -- '*.md' ':!./_docs' |
          grep -v -E -e '^    update' -e '^(Author:|index|new file mode|\-\-\-|\+\+\+) ' |
          sed -e ':a;N;$!ba;s/\n\n\n/\n/g' |
          sed -E '/^\s*$/ i\'$'\n''```' |
          sed -E -e '/^diff / a\'$'\n''\'$'\n''```diff' -e 's|^diff --git a/(.+) b/.+|```\n\n### \1|g' -e 's|^commit (.+)|\n## Commit [\1](https://github.com/adoyle-h/Today-I-Learned/commit/\1)\n|g' |
          sed -E '/^Date: /{N;s/^(Date: .+)\n```/\1/}'

      - name: Create a new GitHub Discussion
        uses: abirismyname/create-discussion@v1.x
        if: ${{ steps.rerport.stdout != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "ADoyle's TIL Weekly ($(date +'%Y-%m-%d'))"
          body: |
            What changed in last week:

            ${{steps.rerport.stdout}}
            ```
          # https://github.com/marketplace/actions/create-github-discussion#obtaining-the-repository-id-and-category-id
          repository-id: MDEwOlJlcG9zaXRvcnk1MzAyMzkzNA==
          category-id: DIC_kwDOAykUvs4CfgjB

      - name: Print discussion url and id
        run: |
          echo discussion-id: ${{steps.create-discussion.outputs.discussion-id}}
          echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}
